### ISSUE TITLE
Check if connections and files are closed properly

### ISSUE THREAD

**Issue by christianmahnke** [subugoe/resolver#3]
Internal bug report:
Hi,

der Resolver antwortet nicht mehr korrekt.

catalina.out hat 1,9 G und meldet

java.net.SocketException: Too many open files
    at java.net.Socket.createImpl(Socket.java:414)
    at java.net.Socket.<init>(Socket.java:388)
    at java.net.Socket.<init>(Socket.java:206)
    at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:86)
    at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:652)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:628)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:497)
    at de.unigoettingen.sub.commons.resolver.LocalResolverConnectorThread.run(LocalResolverConnectorThread.java:73)

**Comment by hwhw** [comment]
very probably fixed by bb066bb6bf5b6217927a0062fefeb6e956576889
